### ISSUE TITLE
Clone to an empty tree fails due to expectation of $nodeScope

### ISSUE THREAD

**Issue by ppuleo** [ppuleo/angular-ui-tree#1]
In PR #510, the `$uiTreeHelper` service's `dragInfo.apply` method's first conditional check expects `this.parent.$nodeScope` to be truthy (not null) even when there is no nesting.

**Comment by joechimo** [comment]
Didn't see this issue, I fixed this in PR #512.  I left a comment on Issue #511 explaining what was incorrect.

**Comment by ppuleo** [comment]
Great, this is fixed.
